#! /usr/bin/env sh

bspc monitor -d I II III IV V VI VII VIII IX X

if [ xrandr --listmonitors | grep -w 'HDMI-2' ]; then
	bspc monitor HDMI-2 -d 'HDMI-2:1';
fi

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move
bspc config external_rules_command "$(which external_rules)"

bspc rule -a Firefox desktop=^2
bspc rule -a Brave-browser desktop=^2

# polybar -l info example 2>/tmp/polybar.log

feh --bg-fill ~/Downloads/1280px-Mandel_zoom_00_mandelbrot_set.jpg

systemctl --user import-environment;
systemctl --user restart wm.target
